# Generated by Django 2.1.5 on 2019-03-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('team_name', models.CharField(max_length=200)),
                ('wiki', models.URLField()),
                ('location', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=200)),
                ('project_title', models.CharField(max_length=200)),
                ('track', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('parts', models.URLField()),
                ('medal', models.CharField(max_length=200)),
                ('nominations', models.CharField(max_length=200)),
                ('awards', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RichPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('networth', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
            ],
        ),
    ]
